// // let a = Infinity*Infinity
// // console.log(a)
// // let b=4; b+=3;
// // let e=10; e **= 5; 
// // console.log(b,e)
// //  console.log(2=="2")
// //  console.log(2==="2")
// //  console.log(2!=="2")
// //  console.log("2"!=2)
 
// let a = 1
// let b = 103

// result = a & b
// console.log(result)


// let age =18;
// let resultt = (age>=18)?"eligible":"not eliogible";
// console.log(resultt);






// function sum()
// {
//     let i;
//     let um=0;
//     for (i=1;i<=100;i++){
//         if(i%2==0){
//             um = um+i;
//         }
//     }
//     return um;
// }
// let ui= sum();
// console.log(ui)







// function great(a,b)
// {
//     let u = (a>b)? a:b;
// return u;
// }
// console.log(great(46,84))




// function dis (df){
//     let d = df-( 0.25*df);
//     return d
// }
// console.log(dis(78000))





// function avg(h,j,k){
//     let a = (h+j+k)/3;
//     return a;
// }
// console.log(avg(10,20,30))


// function newavg(a)
// {let i;
//     let avg;
//     let sum=0;
//     for(i=0;i<=a;i++)
//     {
//         sum = sum+i;
        
//     }
//     avg= sum/a;
//     return avg;

// }
// console.log(newavg(187))







console.log(4&2/5*2+2)
console.log(2**3**2)
console.log(3|2*(4**2))
console.log(5&&3)
console.log(3||" ")
console.log(typeof(+[]))
/*

*/
console.log("hello"&&0&&5&&9)
console.log(9&&true||false&&true)
console.log((5||false||"hello")&&true)
console.log(5&&7&&9&&true)
console.log(5||6||7||8||9||false)
console.log(5|2)